name: Generate Thumbnails

on:
  pull_request:
    branches:
      - main

jobs:
  run-makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up GraphicsMagick
        run: sudo apt-get update && sudo apt-get install -y graphicsmagick

      - name: Run Makefile
        run: |
          cd posts
          make thumbs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-generate thumbnails"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}