name: Generate Thumbnails

on:
  pull_request:
    branches:
      - main

jobs:
  generate-thumbnails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GraphicsMagick
        run: sudo apt-get update && sudo apt-get install -y graphicsmagick

      - name: Run thumbnail generation script
        run: make thumbs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-generate thumbnails"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
